# Generated by Django 5.2.16 on 2026-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
