# Generated by Django 6.0.7 on 2026-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image_url',
        ),
        migrations.AddField(
            model_name='eventitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
