# Generated by Django 6.0.7 on 2026-08-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_eventitem_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero-carousel/')),
                ('button_text', models.CharField(blank=True, max_length=80)),
                ('button_link', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Carousel Item',
                'verbose_name_plural': 'Hero Carousel Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
